Repository DibiDibiDeep/Final-back, pull requests merged in 2024-09, with the labels that each got.

#24 [feature/fairy0910] user login 부분 수정
  build.gradle
  http/alim.http
  http/alimInf.http
  http/baby.http
  http/babyPhoto.http
  http/book.http
  http/fairyTale.http
  http/page.http
  http/user.http
  src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
  src/main/java/com/example/finalproj/BabyPhoto/entity/BabyPhoto.java
  src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
  src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
  src/main/java/com/example/finalproj/Book/controller/BookController.java
  src/main/java/com/example/finalproj/Book/entity/Book.java
  src/main/java/com/example/finalproj/Book/repository/BookRepository.java
  src/main/java/com/example/finalproj/Book/service/BookService.java
  src/main/java/com/example/finalproj/FairyTale/controller/FairyTaleController.java
  src/main/java/com/example/finalproj/FairyTale/repository/FairyTaleRepository.java
  src/main/java/com/example/finalproj/FairyTale/service/FairyTaleService.java
  src/main/java/com/example/finalproj/Page/controller/PageController.java
  src/main/java/com/example/finalproj/Page/entity/Page.java
  src/main/java/com/example/finalproj/Page/repository/PageRepository.java
  src/main/java/com/example/finalproj/Page/service/PageService.java
  src/main/java/com/example/finalproj/baby/controller/BabyController.java
  src/main/java/com/example/finalproj/baby/entity/Baby.java
  src/main/java/com/example/finalproj/baby/repository/BabyRepository.java
  src/main/java/com/example/finalproj/baby/service/BabyService.java
  src/main/java/com/example/finalproj/security/JwtTokenProvider.java
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/java/com/example/finalproj/user/entity/User.java
  src/main/java/com/example/finalproj/user/repository/UserRepository.java
  src/main/java/com/example/finalproj/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/init.sql
Labels: enhancement

#44 [기능 수정] 모든 오리진 허용, google login부분 로깅 추가
  src/main/java/com/example/finalproj/config/WebConfig.java
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/resources/application.yml
Labels: bug

#47 [기능 수정] User 구글 로그인에 관한 내용 전면 수정 & CalendarPhotoInf findById 생성
  build.gradle
  src/main/java/com/example/finalproj/CalendarPhotoInf/controller/CalendarPhotoInfController.java
  src/main/java/com/example/finalproj/CalendarPhotoInf/repository/CalendarPhotoInfRepository.java
  src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/java/com/example/finalproj/user/entity/User.java
  src/main/java/com/example/finalproj/user/repository/UserRepository.java
  src/main/java/com/example/finalproj/user/service/UserService.java
Labels: enhancement

#53 [기능수정] UserController 더미데이터 생성( userId 5, babyId 6 )
  src/main/java/com/example/finalproj/user/controller/UserController.java
Labels: bug

#57 [기능 생성]시큐리티 관련 코드 생성
  build.gradle
  src/main/java/com/example/finalproj/config/SecurityConfig.java
  src/main/java/com/example/finalproj/config/auth/CustomOAuth2UserService.java
  src/main/java/com/example/finalproj/config/auth/OAuthAttributes.java
  src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
  src/main/java/com/example/finalproj/config/auth/dto/SessionUser.java
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/java/com/example/finalproj/user/entity/User.java
  src/main/resources/application.yml
Labels: enhancement

#63 [기능 생성] chat controller 생성
  src/main/java/com/example/finalproj/Chat/controller/ChatController.java
  src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
  src/main/java/com/example/finalproj/Chat/repository/ChatRepository.java
  src/main/java/com/example/finalproj/Chat/service/ChatService.java
  src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
  src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
  src/main/java/com/example/finalproj/user/service/UserService.java
Labels: enhancement

#68 [기능 수정] chatbot, baby 수정 api 수정
  src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
  src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
  src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
  src/main/java/com/example/finalproj/Chat/controller/ChatController.java
  src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
  src/main/java/com/example/finalproj/Chat/repository/ChatRepository.java
  src/main/java/com/example/finalproj/Chat/service/ChatService.java
  src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
  src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
  src/main/java/com/example/finalproj/user/service/UserService.java
Labels: enhancement

#74 [기능 수정]0928 BabyPhotoController, Jwt 필터링, jaxb gradle 추가 및 ChatController 토큰설정
  build.gradle
  src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
  src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
  src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
  src/main/java/com/example/finalproj/Chat/controller/ChatController.java
  src/main/java/com/example/finalproj/config/WebConfig.java
  src/main/java/com/example/finalproj/security/JwtAuthenticationFilter.java
  src/main/java/com/example/finalproj/security/JwtTokenProvider.java
Labels: bug

#75 [기능수정] 구글 로그인 redirect uri 환경변수로 설정
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
Labels: enhancement

#83 [기능 수정] chatbot mlService 기능 동작 및 baby-photo 변경
  http/babyPhoto.http
  src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
  src/main/java/com/example/finalproj/BabyPhoto/entity/BabyPhoto.java
  src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
  src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
  src/main/java/com/example/finalproj/Chat/controller/ChatController.java
  src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
  src/main/java/com/example/finalproj/Chat/service/ChatService.java
  src/main/java/com/example/finalproj/baby/controller/BabyController.java
  src/main/java/com/example/finalproj/baby/service/BabyService.java
  src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
  src/main/java/com/example/finalproj/user/controller/UserController.java
  src/main/java/com/example/finalproj/user/repository/UserRepository.java
  src/main/java/com/example/finalproj/user/service/UserService.java
Labels: documentation
